project:
  type: website
  output-dir: docs

website:
  title: "AM"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Blog
        href: blog/index.qmd
      - text: Alex Meng's Notes
        href: notes_output/index.html
format:
  html:
    theme: united
    toc: false  # disables right nav


