# Optical Computing {.unnumbered}

Wetzstein, G., Ozcan, A., Gigan, S. et al. Inference in artificial intelligence with deep optics and photonics. Nature 588, 39–47 (2020). https://doi.org/10.1038/s41586-020-2973-6

General Optical computing is not practical yet, but using optics for inference for visual computing applications is practical. This paper is a review on recent work on optical computing for AI.

**Motivation 1:** Edge devices (cameras, cars, robots, headsets, IoT) need leaner (low latency, light, small, low power) computational imaging systems.

Optical computing systems promise small form factor, massive parallelism, little to no power consumption. [Optical interconnects are already widely used in data centers today](https://nvidianews.nvidia.com/news/nvidia-spectrum-x-co-packaged-optics-networking-switches-ai-factories).

Linear optical elements can calculate convolution, fourier transforms, random projections, as a byproduct of light-matter interaction. These operations are what's needed for DNNs.

"Incorporating all-optical nonlinearities into photonic circuits is one of the key requirements for truly deep photonic networks. Yet, the challenge of efficiently implementing photonic nonlinear activation functions at low optical signal intensities was one of the primary reasons that interest in ONNs waned in the 1990s. Creative approaches from the last decade, such as nonlinear thresholders based on all-optical micro-ring resonators35, saturable absorbers29,36, electro-absorption modulators37, or hybrid electro-optical approaches38, represent possible solutions for overcoming this challenge in the near future. "

[Although programmability has traditionally been more difficult with photonic systems, first steps towards simplifying the process have recently been demonstrated](https://doi.org/10.1103/PhysRevX.9.021032)

"One direction that seems particularly well suited for optical and photonic processing is **optical inference with incoherent light to rapidly process scene information under ambient lighting conditions**. Such an approach presents many exciting opportunities for autonomous vehicles, robotics and computer vision, which we discuss next."


