project:
  type: website

website:
  title: "Alex Meng's Blog"
  navbar:
    background: primary
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: united
    css: styles.css



