# Maxwell's Equations - Dan Fleisch {.unnumbered}

Website: [Official Website](https://www.danfleisch.com/maxwell/)

## 1 Gauss’s law for electric fields

### Introduction

<details>
<summary>Expand</summary>

- What are the two kinds of Electric Fields in Maxwell's Equation?
  
<details>
<summary>Answer</summary>
* Electrostatic Fields (from electric charge)
* Induced Electric Field (from changing magnetic field)
</details>

- What type of fields does Gauss's law deal with?
  
<details>
<summary>Answer</summary>
Electrostatic Fields (from electric charge)
</details>

</details>

### Integral Form of Gauss's Law

<details>
<summary>Expand</summary>

Electric charge produces an electric field. The flux of that field passing through any closed surface is proportional to the total charge contained within that surface.

$$\oint_S \vec{E} \cdot \hat{n} da = \frac{q_{enc}}{\epsilon_0}$$

::: {.callout-tip collapse="true"}
#### Expand To Learn About Left Hand Side

<!-- <details>
<summary>Expand</summary> -->

* What does the left hand side represent?

<details>
<summary>Answer</summary>
The number of electric field lines (AKA electric flux) passing through a closed surface $S$.
</details>

* What is Electric field?

<details>
<summary>Answer</summary>
The electrical force exerted on one coulomb of charge at that point in space is the electric field at that location.

$$\vec{E} = \frac{\vec{F}_e}{q_0}$$

$\vec{E}$ has units of $\frac{N}{C} = \frac{V}{m}$

Spacing of electric field lines tells you the strength of it.

* Electric field lines go from positive to negative
* Electric field lines vector sums, so they never cross

</details>

- Why do physicists and engineers always talk about small test charges? 

<details>
<summary>Answer</summary>
Because the job of
this charge is to test the electric field at a location, not to add another electric field into the
mix (although you can’t stop it from doing so). Making the test charge infinitesimally
small minimizes the effect of the test charge’s own field.
</details>

- What is the dot product? Why are we taking the dot product between $\vec{E}$ and $\hat{n}$ in Gauss's Law?

<details>
<summary>Answer</summary>
Consider vectors $\vec{A}$ and $\vec{B}$ in space.

What is the projection of $\vec{A}$ onto $\vec{B}$? From trig, it's $|A| \cos \theta$. 

Now the dot product is that projection, multiplied by the magnitude of $\vec{B}$.

$$\vec{A} \cdot \vec{B} = |A| |B| \cos \theta$$

</details>


- What is $\hat{n}$?

<details>
<summary>Answer</summary>
It is the unit normal vector, which has a length of one, and points in the direction perpendicular to the surface.

Note that since $da$ is the tiny amount of area we are considering

$$\hat{n} da = d \vec{a}$$
</details>


- What is the difference between closed surface and open surface?

<details>
<summary>Answer</summary>

* Open Surface - any surface for which it is possible to get from one side to the other without going through the surface
* Closed Surface - a surface that divides space into an "inside" and "outside". Unit Normal Vector $\hat{n}$ always points outwards, away from the volume enclosed by the surface.
</details>

- What does $\vec{E} \cdot \hat{n}$ represent?

<details>
<summary>Answer</summary>
The component of the electric field vector that is perpendicular to the surface.

$$\vec{E} \cdot \hat{n} = |\vec{E}| \cos \theta$$

</details>

- How do you find the mass of a surface with varying density function $\sigma(x, y)$?

<details>
<summary>Answer</summary>
Since mass is density times volume, we can write:

$$Mass = \sigma \cdot Area$$

$$Mass_S = \Sigma_{i = 1}^{N} \sigma_i \cdot Area_i$$

If we let Areas to become infinitesimally small $dA$, we get
$$Mass = \int_{S} \sigma dA$$

This is a *surface intergal*.
</details>

- What does $\int_S \vec{A} \cdot \hat{n} da$ represent?

<details>
<summary>Answer</summary>
It represents the flux of a vector field.

What's a vector field?

It is magnitude and direction quantities distributed in space.

* Scalar Field - something like temperature distribution in a room, where at each point theres a number
* Vector Field - something like flow of fluid, there at every point it has a speed and direction
</details>

- What's flux $\Phi$?

<details>
<summary>Answer</summary>
Flux $\Phi$ of a field over a surface is the amount of flow through that surface.

$$\Phi = \vec{A} \cdot \hat{n} \times (Surface Area)$$
</details>

<!-- end left hand side -->
<!-- </details> -->
:::

::: {.callout-tip collapse="true"}
#### Expand To Learn About Right Hand Side

- What is the right hand side in words?
  
<details>
<summary>Answer</summary>
The total amount of enclosed charge normalized by the permittivity of free space.
</details>

- What is $\epsilon_0$ and why is it there?
  
<details>
<summary>Answer</summary>
It is called the permitivity of free space or "vacuum permitivity".

$$\epsilon_0 = 8.854 \times 10^{-12} \frac{F}{m}$$

When we say the permitivity of a material, when are referring to its reponse to an electric field. It is also the key parameter in determining the speed at which an electromagnetic wave propagates through that medium.

High permitivity means it provides higher capacitance. 

In Gauss's Law, $\epsilon_0$ acts as a proportionality constant that relates electric flux to enclosed charge.
</details>

:::

::: {.callout-tip collapse="true"} 
#### Exercises

- Five point charges are enclosed in a cylindrical surface $S$. If the
values of the charges are $q_1 = +3 nC$, $q_2 = -2 nC$, $q_3 = +2 nC$, $q_4 = +4 nC$, and $q_5 = -1 nC$, find the total flux through $S$.

<details>
<summary>Answer</summary>

$$\sum_{i=1}^{5} q_i = 3 - 2 + 2 + 4 - 1 = 6 nC = 6 \times 10^{-9} C$$

$$\Phi_E = \frac{q_enc}{\epsilon_0} = \frac{6 \times 10^{-9}C}{8.854 \times 10^{-12} \frac{C}{V \cdot m}} = \boxed{678 \hspace{1mm} Vm}$$

</details>

:::

<!-- end integral form  -->
</details>




### Differential Form of Gauss's Law
<!-- begin differential form -->

<details>
<summary>Expand</summary>

The electric field produced by electric diverges from positive charge and converges upon negative charge.

$$\vec{\nabla} \cdot \vec{E} = \frac{\rho}{\epsilon_0}$$

::: {.callout-tip collapse="true"}
#### Expand To Learn About Left Hand Side

<!-- <details>
<summary>Expand</summary> -->

- What does the left hand side represent?

<details>
<summary>Answer</summary>
<!-- TODO -->
The tendency of electric field to flow away from a point in space - AKA the divergence.
</details>


- What is the difference between differential and integral form of Gauss's Law?

<details>
<summary>Answer</summary>
<!-- TODO -->
Differential deals with individual points in space, whereareas integral deals with a closed surface.
</details>

- What is $\vec{\nabla}$?

<details>
<summary>Answer</summary>
<!-- TODO -->
It is called "del" or "nabla". It tells you to take the derivative of what ever quantity comes after it. 

$$\vec{\nabla} =\hat{i} \frac{\partial}{\partial x} + \hat{j} \frac{\partial}{\partial y} + \hat{k} \frac{\partial}{\partial z}
$$ 

It is an *mathematical operator*, which just means that it needs something to act on and cannot just appear by itself.

$\vec{\nabla}$ is gradient, $\vec{\nabla} \cdot$ is divergence, and $\vec{\nabla} \times$ is curl.
</details>

- What is $\vec{\nabla} \cdot$ specifically?

<details>
<summary>Expand</summary>

Oliver Heaviside suggested the word "divergence" to describe the rate at which electric field flow outwards from a positive charge.

* source - diverge from that point (positive charge for electric field)
* sink - converge to that point (negative charge for magnetic field)

</details>




<!-- end left hand side -->
:::

::: {.callout-tip collapse="true"}
#### Expand To Learn About Right Hand Side

- What is the right hand side in words?
  
<details>
<summary>Answer</summary>
<!-- TODO -->
</details>
:::

::: {.callout-tip collapse="true"} 
#### Exercises

- Five point charges are enclosed in a cylindrical surface $S$. If the
values of the charges are $q_1 = +3 nC$, $q_2 = -2 nC$, $q_3 = +2 nC$, $q_4 = +4 nC$, and $q_5 = -1 nC$, find the total flux through $S$.

<details>
<summary>Answer</summary>

$$\sum_{i=1}^{5} q_i = 3 - 2 + 2 + 4 - 1 = 6 nC = 6 \times 10^{-9} C$$

$$\Phi_E = \frac{q_enc}{\epsilon_0} = \frac{6 \times 10^{-9}C}{8.854 \times 10^{-12} \frac{C}{V \cdot m}} = \boxed{678 \hspace{1mm} Vm}$$

</details>

:::

</details>
<!-- end differential form -->


<!-- <details>
<summary>Expand</summary>
</details> -->