# Applied Electromagnetics {.unnumbered}

## Electromagnetic Waves

* Maxwell's Equations predict waves
* Derivation and solution of the wave equation

In source-free media, $\vec{J} = 0$ and $\rho_V = 0$, maxwell's equations in the frequency-domain become

**Curl Equations**

$$\nabla \times \vec{E} = -j\omega \vec{B}$$
$$\nabla \times \vec{H} = -j\omega \vec{D}$$

**Divergence Equations**

$$\nabla \cdot \vec{D} = 0$$
$$\nabla \cdot \vec{B} = 0$$

**Constitutive Relations**

$$\vec{D} = \epsilon \vec{E}$$
$$\vec{B} = \epsilon \vec{H}$$

Substituting constitutive relations into the curl equations, we get:

$$\nabla \times \vec{E} = -j \omega \mu \vec{H}$$

If we have an oscillating $\vec{H}$ that will induce a circulating $\vec{E}$

$$\nabla \times \vec{H} =  - j \omega \epsilon \vec{E}$$

If we have an oscillating $\vec{E}$ that will induce a circulating $\vec{H}$

An oscillating (for some reason) electric field, oscillating electric field will induce a circulating magnetic field. 

## Derive Wave Equation

**Curl Equations with Constitutive Relations plugged in** 

$$
\nabla \times \vec{E} = -j \omega [\mu] \vec{H} \tag{1}
$$

$$
\nabla \times \vec{H} = j \omega [\epsilon] \vec{E} \tag{2}
$$


**Solve (1) for $\vec{H}$**

$$\frac{1}{j \omega [\mu]}  \nabla \times \vec{E} = \vec{H}\tag{3}$$

**Substitute (3) into (2)**

$$
\nabla \times \left( \frac{1}{j \omega [\mu]}  \nabla \times \vec{E} \right) = -j \omega [\epsilon] \vec{E}
$$

There you go!! That is the wave equation.

$$
\nabla \times \left( \frac{1}{[\mu]}  \nabla \times \vec{E} \right) = (j\omega) (-j \omega) [\epsilon] \vec{E}
$$

$$
\nabla \times \left( \frac{1}{[\mu]}  \nabla \times \vec{E} \right) = \omega^2 [\epsilon] \vec{E}
$$

Here we have anisotropic permeability and permitivity, it is usually used in computer simulations. 

We want to bring permeability outside of that curl, so if permeability is inhomogeneous, it is a function of position so we cannot bring it outside.

If we assume **linear, homogeneous, anisotropic materials**,

$$
\nabla \times \left( \frac{1}{[\mu]}  \nabla \times \vec{E} \right) = \omega^2 [\epsilon] \vec{E}
$$

$$
\nabla \times \left(  \nabla \times \vec{E} \right) = \omega^2 \mu \epsilon \vec{E}
$$

Vector Identity: $\nabla \times  \nabla \times \vec{A} = \nabla ( \nabla \cdot \vec{A}) - \nabla^2 \vec{A}$

$$
\nabla ( \nabla \cdot \vec{E}) = \nabla^2 \vec{E} + \omega^2 \mu \epsilon \vec{E} \tag{4}
$$

Since $\nabla \cdot \vec{D} = 0$, 

$$\nabla \cdot \vec{D} = 0 \implies \nabla \cdot (\epsilon \vec{E}) = 0$$

$$\nabla \cdot \vec{E} = 0$$

So the left-hand side of equation (4) becomes 0, we get

$$\boxed{\nabla^2 \vec{E} + \omega^2 \mu \epsilon \vec{E} = 0} \tag{5}$$

Let's call $\omega^2 \mu \epsilon = k^2$, and $k$ is called the **wave number**

$$k = \omega \sqrt{\mu \epsilon}$$

We can also define $-\omega^2 \mu \epsilon = \gamma^2$, $\gamma$ is called the complex propagation constant.

$$\gamma^2 = -k^2$$

So we can write frequency-domain wave equation as

$$\boxed{\nabla^2 \vec{E} + k^2 \vec{E} = 0}$$
$$\boxed{\nabla^2 \vec{E} - \gamma^2 \vec{E} = 0}$$

## Components Decouple in LHI Media

LHI stands for Linear, homogeneous, isotropic,
$$\nabla^2 \vec{E} + k^2 \vec{E} = 0$$

$$\nabla^2 \left( E_x \hat{a}_x + E_y \hat{a}_y + E_z \hat{a}_z \right) + k^2 \left( E_x \hat{a}_x + E_y \hat{a}_y + E_z \hat{a}_z \right) = 0$$

**Distribute**

$$ \nabla^2 E_x \hat{a}_x + \nabla^2 E_y \hat{a}_y + \nabla^2 E_z \hat{a}_z +  k^2 E_x \hat{a}_x + k^2 E_y \hat{a}_y + k^2 E_z \hat{a}_z = 0$$

$$ \left( \nabla^2 E_x \hat{a}_x  + k^2 E_x \hat{a}_x \right) + \left( \nabla^2 E_y \hat{a}_y + k^2 E_y \hat{a}_y \right) + \left( \nabla^2 E_z \hat{a}_z + k^2 E_z \hat{a}_z \right) = 0$$

So each individual component has to equal to $0$, so we can take our *vector equation* and turn it into *three scalar* equations

$$\nabla^2 E_x \hat{a}_x  + k^2 E_x \hat{a}_x  = 0$$
$$\nabla^2 E_y \hat{a}_y + k^2 E_y \hat{a}_y  = 0$$
$$ \nabla^2 E_z \hat{a}_z + k^2 E_z \hat{a}_z = 0$$

They have the same general solution... so we can just solve 

$$\nabla^2 E + k^2 E = 0$$

and reuse the solution to all three scalar equations.

**mathematical solution**


$$\nabla^2 E + k^2 E = 0$$

$$\implies E(\vec{r}) =  E_{0}^{+} e^{-j \vec{k} \cdot \vec{r}} + E_{0}^{-} e^{+j \vec{k} \cdot \vec{r}}$$

* $E_{0}^{+} e^{-j \vec{k} \cdot \vec{r}}$ is the forward wave
* $E_{0}^{-} e^{+j \vec{k} \cdot \vec{r}}$ is the backward wave

$$\vec{E}(\vec{r}) = E_x(\vec{r}) \hat{a}_x + E_y(\vec{r}) \hat{a}_y + E_z(\vec{r}) \hat{a}_z$$

## General Expression for a Plane wave

$$\vec{E}(\vec{r}) = \vec{P} e^{-j \vec{k} \cdot \vec{r}} \tag{frequency-domain}$$
$$\vec{E}(\vec{r}, t) =  \vec{P} \cos(\omega t - \vec{k} \cdot \vec{r}) \tag{time-domain}$$

* $\vec{r} \equiv x \hat{a}_x + y \hat{a}_y + z \hat{a}_z$ 
* $\vec{E} \equiv \text{total electric field intensity}$ 
* $\vec{P} \equiv \text{polarization vector}$ 
* $\vec{k} \equiv \text{wave vector}$ 
* $\omega \equiv 2 \pi f \equiv \text{angular frequency}$s
* $t \equiv \text{time}$

So for the magnetic field, we can just use this result back into maxwell's equations,

$$\nabla \times \vec{E} = -j \omega \mu \vec{H} \tag{Faraday's Law}$$
$$\nabla \times \left(  \vec{P} e^{-j \vec{k} \cdot \vec{r}} \right) = -j \omega \mu \vec{H}$$

$$\boxed{\frac{1}{\omega \mu} \left(  \vec{k} \times \vec{P} \right) e^{-j \vec{k} \cdot \vec{r}} = \vec{H}}$$

### Solution in terms of $\gamma$

$$E(\vec{r}) = E_{0}^{+} e^{-\vec{\gamma} \cdot \vec{r}} + E_{0}^{-} e^{+\vec{\gamma} \cdot \vec{r}}$$

$$E(\vec{r}) = \vec{P} e^{-\vec{\gamma} \cdot \vec{r}} \tag{frequency domain}$$

$$\vec{H} = \frac{1}{j \omega \mu} ( \vec{\gamma} \times \vec{P}) e^{-\vec{\gamma} \cdot \vec{r}}$$

The wave vector and propagation constant are related through:

$$\vec{\gamma} = j \vec{k}$$







